Armory & aSnip additions
Version 2.5

diff --git a/sifter b/sifter
--- a/sifter
+++ b/sifter
@@ -1,8 +1,11 @@
 #!/bin/bash
-RED='\033[0;31m'
-NC='\033[0m'
 ORNG='\033[0;33m'
+NC='\033[0m'
 W='\033[1;37m'
+LP='\033[1;35m'
+YLW='\033[1;33m'
+LBBLUE='\e[104m'
+RED='\033[0;31m'
 ARG=$2                                         # IP addition argument
 # Help Menu
 usage() {                                      # Function: Print a help message.
@@ -66,7 +69,7 @@ dom_mods(){
   figlet -f mini "Domain-Focused Modules"
   echo -e "${ORNG}"
   PS3='What tool would you like to use?'
-          options=("DnsTwist" "DomainFuzz" "Sublist3r" "Armory" "Back" "Quit")
+          options=("DnsTwist" "DomainFuzz" "Sublist3r" "Back" "Quit")
           select opt in "${options[@]}"
           do
                   case $opt in
@@ -80,10 +83,6 @@ dom_mods(){
 
                             "Sublist3r")
                                 ./modules/dommods/sublist3r.sh
-                                ;;
-
-                            "Armory")
-                                ./modules/dommods/armory.sh
                                 ;;
 
                             "Back")
@@ -103,20 +102,24 @@ net_mods(){
   figlet -f mini "Network-Focused Modules"
   echo -e "${ORNG}"
   PS3='What tool would you like to use?'
-          options=("Scan for Live-Hosts" "nMap" "AttackSurfaceMapper" "Back"  "Quit")
+          options=("nMap" "AttackSurfaceMapper" "Armory" "aSnip" "Back"  "Quit")
           select opt in "${options[@]}"
           do
                   case $opt in
-                            "Scan for Live-Hosts")
-                                ./modules/netmods/check.sh
-                                ;;
-
                             "nMap")
                                 ./modules/netmods/nmap.sh
                                 ;;
 
                             "AttackSurfaceMapper")
                                 ./modules/netmods/asm.sh
+                                ;;
+
+                            "Armory")
+                                ./modules/netmods/armory.sh
+                                ;;
+
+                            "aSnip")
+                                ./modules/netmods/asnip.sh
                                 ;;
 
                             "Back")
@@ -204,7 +207,7 @@ web_mods(){
 ex_mods(){
   echo -e "${RED}"
   figlet -f mini "Exploitation Modules"
-  echo -e "${NC}"
+  echo -e "${ORNG}"
   PS3='What tool would you like to use?'
         options=("ActiveReign" "TigerShark" "iSpy" "ShodanSploit" "Back" "Quit")
         select opt in "${options[@]}"
@@ -274,12 +277,13 @@ ex_mods(){
                                 ;;
                 esac
         done
+    echo -e "${NC}"
 }
 # Web-App Modules
 webapps(){
   echo -e "${RED}"
   figlet -f mini "WebApp Modules"
-  echo -e "${NC}"
+  echo -e "${ORNG}"
   PS3='What tool would you like to use?'
         options=("Sitadel" "wafw00f" "Photon" "Back" "Quit")
         select opt in "${options[@]}"
@@ -306,6 +310,117 @@ webapps(){
                             ;;
                 esac
         done
+    echo -e "${NC}"
+}
+# Host Check
+check_hosts(){
+    echo -e "${ORNG}Host Check${NC}"
+    echo -e "${ORNG}***********${NC}"
+    rm files/pingtest_raw.pass files/pingtest.pass files/pingtest_pass.txt
+
+    for name in `cat files/host_list.txt`
+
+            do
+                ping -c 1 $name
+                    if [[ $? == 0 ]]; then
+                        echo -e "${LP}=================="
+                        echo -e "\e[95m$name Alive\e[0m" && echo $name >> files/pingtest_raw.pass
+                        echo -e "${LP}==================${NC}"
+                    else
+                        echo -e "${RED}=================="
+                        echo -e "\e[1;31m$name Dead\e[0m" && echo $name >> files/pingtest_raw.fail
+                        echo -e "${RED}==================${NC}"                        
+                    fi
+            done
+
+                sleep 5
+
+            echo "============================================================================================================================="
+
+            echo -e "\e[95mPingtest_Pass\e[0m"
+            echo $'\e[95m*************\e[0m'
+	        cat files/pingtest_raw.pass | sort | uniq > files/pingtest.pass
+            echo -e "${YLW}"
+	        cat files/pingtest.pass
+	        echo -e "${NC}"
+	        sed -e 's/^/http:\/\//' files/pingtest.pass > files/pingtest_pass.txt
+
+            echo "============================================================================================================================="
+
+            echo -e "\e[1;31mPingtest_Fail\e[0m"
+            echo $'\e[1;31m*************\e[0m'
+            cat files/pingtest_raw.fail | sort | uniq > files/pingtest.fail
+            echo -e "${YLW}"
+	        cat files/pingtest.fail
+	        echo -e "${NC}"
+            sleep 5
+            menu
+}
+# List Arguments for Options Below
+ip_add() {
+  echo -e "${W}Please enter your target:${NC}"
+  read IP_ANS
+  sleep 1
+  echo "$IP_ANS" >> files/host_list.txt
+  ip_q
+}
+ip_q() {
+  echo -e "${W}Would you like to add another?(y/n)${NC}"
+	read ANS
+	sleep 1
+	if [[ $ANS == y ]]; then
+	  ip_add
+	else
+	  menu
+	fi
+}
+# List Editor
+list_editor(){
+    echo -e "${RED}List Editor${NC}"
+    echo -e "${RED}************${YLW}"
+    cat files/host_list.txt
+    echo -e "${ORNG}"
+            PS3='What would you like to do?'
+            options=("Check" "List" "Add" "Remove" "Back")
+            select opt in "${options[@]}"
+            do
+                    case $opt in
+                            "Check")
+                                check_hosts
+                                sleep 5
+                                list_editor
+                                ;;
+
+                            "List")
+                                echo -e "${YLW}"
+                                cat files/host_list.txt
+                                echo -e "${NC}"
+                                sleep 5
+                                list_editor
+                                ;;
+
+                            "Add")
+                                echo -e "${W}Type the IP or hostname you would like to add${NC}"
+			                    sleep 5
+                                read LTARGET
+                                echo "$LTARGET" >> files/host_list.txt
+                                echo -e "${W}Target Added!${NC}"
+                                ip_q
+                                ;;
+
+                            "Remove")
+                                nano files/host_list.txt
+                                echo -e "${W}Target Removed!${NC}"
+                                sleep 5
+                                list_editor
+                                ;;
+
+                            "Back")
+                                menu
+                                ;;
+                    esac
+            done
+    echo -e "${NC}"
 }
 # Module Menu
 modules(){
@@ -354,24 +469,25 @@ modules(){
 }
 # Menu
 menu(){
-    echo -e "${RED}"
+    echo -e "${ORNG}"
     figlet -f big "..SifteR.."
-    echo -e "${PPL}"
+    echo -e "${LP}"
     figlet -f small "s1l3nt78"
-    echo -e "${ORNG}////////========RubY_(v2.2)========\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\${NC}"
-    echo -e "${LP}==Hit Ctrl + c at any time to quit Sifter==${NC}"
+    echo -e "${RED}////////========RubY_(v2.2)========\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\${NC}"
+    echo -e "${W}==Hit Ctrl + c at any time to quit Sifter==${NC}"
     arg=$1
+    echo -e "${ORNG}"
     PS3='What would you like to do?'
-            options=("Check" "Edit List" "Parse Results to Modules" "Update" "Quit")
+            options=("Check Hosts" "Edit Host List" "Parse Results to Modules" "Update" "Quit")
             select opt in "${options[@]}"
             do
                 case $opt in
-                    "Check")
-                        ./modules/netmods/check.sh
+                    "Check Hosts")
+                        check_hosts
                         ;;
 
-                    "Edit List")
-                        ./modules/netmods/editor.sh
+                    "Edit Host List")
+                        list_editor
                         ;;
 
                     "Parse Results to Modules")
@@ -387,6 +503,7 @@ menu(){
                         ;;
                 esac
             done
+    echo -e "${NC}"
 }
 # Update
 update(){
